version: "3"

services:
    mongo:
        container_name: mongodatabase
        restart: always
        image: mongo
        networks:
            - red_privada
        volumes: 
            - mongo-data:/data/db
        expose:
            - ${PORT}
    server:
        depends_on:
            - mongo
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: servidor
        restart: always
        expose: 
            - ${BACKENDPORT}
        links:
            - mongo
        networks:
            - red-proxy
            - red_privada
        environment: 
            VIRTUAL_HOST: api.mmexp.informatica.uv.cl
    react-app:
        depends_on:
            - server
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        container_name: react-application
        stdin_open: true
        networks: 
            - red-proxy
        environment: 
            VIRTUAL_HOST: mmexp.informatica.uv.cl
networks: 
    red-proxy:
        external:
            name: network-docker
    red_privada:
        
volumes: 
    mongo-data:
        driver: local